#!/bin/sh

elm -m Main.elm --bundle-runtime --build-dir /tmp/ca-elm-lessons/ && git checkout gh-pages && mv -f /tmp/ca-elm-lessons/Main.html index.html && git commit -m Build && git push origin gh-pages
git checkout master
