#!/bin/sh

for f in *.elm; do
  elm -m "$f" --set-runtime /elm-runtime.js --build-dir /tmp/ca-elm-lessons/ || exit
done

git checkout gh-pages || exit

for f in /tmp/ca-elm-lessons/*.html; do
  l="$(basename -s .html $f | awk '{print tolower($0)}')"
  if [ "$l" == "index" ]; then
    mv -f "$f" "index.html"
  else
    mkdir -p "$l"
    mv -f "$f" "$l/index.html"
  fi
done

git add --all && git commit -m Build #&& git push origin gh-pages

#git checkout master
